#!/usr/bin/env bash

about() {
      cat <<EOF
Consul Leader Election CLI
  author: joe-at-startupmedia

  Available options:
    -d: enable debugging
    -h: print this help page
    -k: pass a specific leader election key
    -t: pass the acl token
    -g: get the current session id
    -i: get the session info
    -I: get the session info by passing the session id
    -L: list sessions
    -D: delete a session by passing the session id
    -a: Acquire a lock from the current session id using the hostname
    -A: Acquire a lock by passing a session id using the hostname
    -w: Watch the session lock
    -n: get sessions by the node id
    -l: get the current leader
    -m: match the current leader against the hostname
    -C: create a new session
  Usage:
    $ cle -L 
        list sessions
    $ cle -gi
        gets the current session info
    $ cli -I xxxxxxx-xxxxxxx-xxxxxxx 
        get the session by its ID
EOF

}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$DIR/utils.bash"
include_env "${DIR}"
deps=("jq" "curl")
require_deps "${deps[@]}"

CONSUL_HOST=${CONSUL_HOST:-"http://localhost:8500"}

SESSION_ID=""

get_session() {
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}"| jq  -r ".[].Session"
}

create_session() {
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -X PUT "${CONSUL_HOST}/v1/session/create"
}

acquire_lock() {
  SESSION_ID="${1}"
  curl \
    --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" \
    --data '{"Node": "'`hostname`'"}' \
    -sX PUT "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}?acquire=${SESSION_ID}" | cap

  RESULT=$(ret)

  if [ "${RESULT}" == "true" ]; then
    echo "Acquired Lock" && exit 0
  elif [ "${RESULT}" == "false"  ]; then
    echo "Did Not Acquire Lock"
  else
    echo "${RESULT}"
  fi
  
  exit 1
}

watch_lock() {
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}"| jq  -r ".[].ModifyIndex" | cap

  MODIFY_INDEX=$(ret)

  if [ -z "${MODIFY_INDEX}" ]; then
    echo "could not obtain ModifyIndex"
    exit 1
  else 
    echo "obtained ModifyIndex: ${MODIFY_INDEX}"
  fi

  echo "watching lock..."
  #this will block until key is modified
  curl \
    --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" \
    -sX GET "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}?index=${MODIFY_INDEX}" | cap
  ret | pipe_to_jq_if_json
}

delete_session() {
  SESSION_ID="${1}"
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -X PUT "${CONSUL_HOST}/v1/session/destroy/${SESSION_ID}"
}

get_node_sessions() {
  NODE_ID=${1}
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/session/node/${NODE_ID}" | cap
  ret | pipe_to_jq_if_json
}

list_sessions() {
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/session/list" | cap
  ret | pipe_to_jq_if_json
}

get_session_info() {
  SESSION_ID="${1}"
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/session/info/${SESSION_ID}" | cap
  ret | pipe_to_jq_if_json
}

get_leader() {
  SESSION_ID="${1}"
  get_session_info "${SESSION_ID}" | jq -r ".[].Node"
}

match_leader() {
  SESSION_ID="${1}"
  get_leader "${SESSION_ID}" | grep -o $(hostname)
}

while getopts ":hdk:t:giI:lmn:LCD:aA:w" opt; do
  case $opt in
    d)
      set -x
      ;;
    k)
      ELECTION_KEY="${OPTARG}"
      ;;
    t)
      ACL_TOKEN="${OPTARG}"
      ;;
    g)
      if [ -z "${ELECTION_KEY}" ]; then
        echo "ELECTION_KEY environment variable is required."
        exit 1
      fi
      SESSION_ID=$(get_session)
      echo "session_id grabbed by election key: $SESSION_ID"
      ;;
    i)
      get_session_info "${SESSION_ID}"
      ;;
    I)
      if [ -z "${SESSION_ID}" ]; then
        SESSION_ID=${OPTARG}
      fi
      get_session_info "${SESSION_ID}"
      ;;
    l)
      if [ -z "${SESSION_ID}" ]; then
        SESSION_ID=${OPTARG}
      fi
      get_leader "${SESSION_ID}"
      ;;
    n)
      get_node_sessions "${OPTARG}"
      ;;
    m)
      match_leader "${SESSION_ID}"
      ;;
    L)
      list_sessions
      ;;
    C)
      create_session
      ;;
    D)
      if [ -z "${SESSION_ID}" ]; then
        SESSION_ID=${OPTARG}
      fi
      delete_session "${SESSION_ID}"
      ;;
    a)
      acquire_lock "${SESSION_ID}"
      ;;
    A)
      if [ -z "${SESSION_ID}" ]; then
        SESSION_ID=${OPTARG}
      fi
      acquire_lock "${SESSION_ID}"
      ;;
    w)
      watch_lock
      ;;
    h)
      about
      ;;
    ?)
      echo "Invalid option: -$OPTARG" >&2
      about
      ;;
  esac
done
