#!/usr/bin/env bash

# See the following consul documentation:
#   https://developer.hashicorp.com/consul/docs/dynamic-app-config/sessions/application-leader-election#acquire-the-lock
#   https://developer.hashicorp.com/consul/api-docs/session

about() {
      cat <<EOF
Consul Leader Election CLI
  author: joe-at-startupmedia

  Available Flags:
    -x: enable debugging
    -v: toggle verbosity
    -h: print this help page
    -k: pass a specific leader election key
    -e: get leader election key/value
    -t: pass the acl token
    -g: get the current session id
    -i: get the session info
    -L: list sessions
    -d: delete the current session
    -a: Acquire a lock from the current session id using the hostname
    -w: Watch the session lock
    -r: Release a lock from the current session id using the hostname
    -n: get sessions by the node id
    -N: get sessions by passing the node id
    -l: get the current leader
    -m: match the current leader against the hostname
    -c: create a new session if one doesn't already exist
    -R: renew a session

  Usage:
    $ cle -L 
        ## list sessions
    $ cle -gi
        ## gets the current session info
    $ cli -I xxxxxxx-xxxxxxx-xxxxxxx 
        ## get the session by its ID
    $ cli -C
        ## create a new session
    $ cli -ga
        ## acquire a lock from the current session
    $ cli -gm
        ## check if the current node is the leader
EOF

}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$DIR/utils.bash"
include_env "${DIR}"
deps=("jq" "curl")
require_deps "${deps[@]}"

CONSUL_HOST=${CONSUL_HOST:-"http://localhost:8500"}

HOSTNAME=${HOSTNAME:-`hostname`}

capture_election_kv() {
  require_election_key
  
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}"| cap
}

get_election_kv() {
  capture_election_kv  
  ret | pipe_to_jq_if_json
}

get_session() {
  capture_node_sessions "${HOSTNAME}"
  RESULT=$(ret)
  RESULT_EMTPTY=$(echo "${RESULT}" | jq -e '. | length == 0')
  if [ -z "${RESULT}" ] || [ "${RESULT_EMTPTY}" == "true" ]; then
    fn_verbose "session was not found from session list"
    return 1
  else
    SESSION_ID=$(echo "${RESULT}" | jq  -r ".[].ID")
  fi
}

create_session() {
  capture_node_sessions "${HOSTNAME}"
  RESULT=$(ret)
  RESULT_EMTPTY=$(echo "${RESULT}" | jq -e '. | length == 0')
  if [ -z "${RESULT}" ] || [ "${RESULT_EMTPTY}" == "true" ]; then
    curl \
      --header "X-Consul-Token: ${ACL_TOKEN}" \
      --data '{"TTL": "15s"}' \
      -sX PUT "${CONSUL_HOST}/v1/session/create" | cap

    ret | pipe_to_jq_if_json
  else
    fn_verbose "session already exists for the current node"
    return 1
  fi
}

capture_renew_session() {
  SESSION_ID="${1}"

  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX PUT "${CONSUL_HOST}/v1/session/renew/${SESSION_ID}" | cap
}

renew_session() {
  capture_renew_session "${1}"
  ret | pipe_to_jq_if_json
}

acquire_lock() {
  SESSION_ID="${1}"
  
  require_election_key
  
  curl \
    --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" \
    --data '{"Node": "'${HOSTNAME}'"}' \
    -sX PUT "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}?acquire=${SESSION_ID}" | cap

  RESULT=$(ret)

  handle_from_bool "${RESULT}" "Acquired Lock" "Did Not Acquire Lock"
}

watch_lock() {
 
  capture_election_kv 
 
  ret | jq  -r ".[].ModifyIndex" | cap

  MODIFY_INDEX=$(ret)

  if [ -z "${MODIFY_INDEX}" ]; then
    fn_verbose "could not obtain ModifyIndex"
    return 1
  else 
    fn_verbose "obtained ModifyIndex: ${MODIFY_INDEX}"
  fi

  fn_verbose "watching lock..."
  
  #this will block until key is modified
  curl \
    --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" \
    -sX GET "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}?index=${MODIFY_INDEX}" | cap

  ret | pipe_to_jq_if_json
}

release_lock() {
  SESSION_ID="${1}"

  require_election_key

  curl \
    --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" \
    --data '{"Node": "'${HOSTNAME}'"}' \
    -sX PUT "${CONSUL_HOST}/v1/kv/${ELECTION_KEY}?release=${SESSION_ID}" | cap

  RESULT=$(ret)

  handle_from_bool "${RESULT}" "Released Lock" "Could Not Release Lock"
}

delete_session() {
  SESSION_ID="${1}"
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX PUT "${CONSUL_HOST}/v1/session/destroy/${SESSION_ID}" | cap

  RESULT=$(ret)
  
  handle_from_bool "${RESULT}" "Deleted Session" "Could not delete session"
}

capture_node_sessions() {
  NODE_ID=${1}
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/session/node/${NODE_ID}" | cap
}

get_node_sessions() {
  capture_node_sessions "${1}"
  ret | pipe_to_jq_if_json
}

capture_sessions() {
   curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/session/list" | cap
}

list_sessions() {
  capture_sessions
  ret | pipe_to_jq_if_json
}

get_session_info() {
  SESSION_ID="${1}"
  curl \
    --header "X-Consul-Token: ${ACL_TOKEN}" \
    -sX GET "${CONSUL_HOST}/v1/session/info/${SESSION_ID}" | cap
  ret | pipe_to_jq_if_json
}

get_leader() {
  capture_election_kv
  LOCK_SESSION_ID=$(ret | jq -r ".[].Session")
  capture_sessions
  ret | jq -r ".[] | select(.ID==\"${LOCK_SESSION_ID}\") | .Node"
}

match_leader() {
  get_leader | grep -o "${HOSTNAME}"
}

require_election_key() {
  if [ -z "${ELECTION_KEY}" ]; then
    fn_verbose "ELECTION_KEY environment variable is required."
    exit 1
  fi
}

while getopts ":hxk:s:t:vegilmnN:LcRdawr" opt; do
  case $opt in
    x)
      set -x
      ;;
    k)
      ELECTION_KEY="${OPTARG}"
      ;;
    s)
      SESSION_ID="${OPTARG}"
      ;;
    t)
      ACL_TOKEN="${OPTARG}"
      ;;
    v)
      VERBOSE=true
      ;;
    e)
      get_election_kv
      ;;
    g)
      get_session
      exit_from_status $?
      fn_verbose "session_id found from hostname: $SESSION_ID"
      ;;
    i)
      get_session_info "${SESSION_ID}"
      ;;
    l)
      get_leader "${SESSION_ID}"
      ;;
    n)
      get_node_sessions "${HOSTNAME}"
      ;;
    N)
      get_node_sessions "${OPTARG}"
      ;;
    m)
      match_leader "${SESSION_ID}"
      ;;
    L)
      list_sessions
      ;;
    c)
      create_session
      exit_from_status $?
      ;;
    R)
      renew_session "${SESSION_ID}"
      ;;
    d)
      delete_session "${SESSION_ID}"
      ;;
    a)
      acquire_lock "${SESSION_ID}"
      ;;
    w)
      watch_lock
      ;;
    r)
      release_lock "${SESSION_ID}"
      ;;
    h)
      about
      ;;
    ?)
      echo "Invalid option: -$OPTARG" >&2
      about
      ;;
  esac
done
