#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$DIR/cle"

while true; do
  sleep 5
  
  if [ -z "${SESSION_ID}" ]; then
    get_session
    if [ -z "${SESSION_ID}" ]; then
      create_session
      continue
    fi
  fi

  capture_renew_session "${SESSION_ID}"
  RENEW_RESULT=$(ret | jq -r '.[0].ID')
  if [ -z "${RENEW_RESULT}" ]; then
    fn_verbose "session renewal encountered an error. creating new session"
    unset SESSION_ID
  else
    acquire_lock "${SESSION_ID}"
  fi
done
