#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$DIR/cle"

VERBOSE=true

create_session

get_session

acquire_lock "${SESSION_ID}"

while true; do
  sleep 5
  renew_session "${SESSION_ID}"
  acquire_lock "${SESSION_ID}"
done
