#!/usr/bin/env bash

about() {
      cat <<EOF
Consul Managment CLI
  author: joe-at-startupmedia

  Available options:
    -d: enable debugging
    -h: print this help page
    -g: generate the CA files
    -c: specify client mode
    -r: generate certificate requests
    -s: sign the certificate requests
    -v: validate the certificate requests
    -A: generate sign and validate certs

  Examples:

    # generate the CA certs
    ./cmc -dg ssh-staging-cmd startup-consul-1

    # generate sign and validate the client certs
    ./cmc -cA
EOF

}

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
DIR_TLS="${DIR}/tls"

#attempt to include the .env file if it exists
FILE="${DIR}/.env" && test -f $FILE && source $FILE

DC="${DC:-dc1}"
SERVERS_COUNT=${SERVERS_COUNT:-1}
TTL=${TTL:-28}
SUBDOMAIN="${SUBDOMAIN:-server}"
DOMAIN=${DOMAIN:-node.consul}

gen_ca() {
  exec_hop_cmd="${1}"
  target="${2}"
  ${exec_hop_cmd} ${target} "rm ~/consul-agent-ca*.pem"
  ${exec_hop_cmd} ${target} "consul tls ca create"
  ${exec_hop_cmd} ${target} "cat ~/consul-agent-ca.pem" > "${DIR_TLS}/consul-agent-ca.pem"
  ${exec_hop_cmd} ${target} "cat ~/consul-agent-ca-key.pem" > "${DIR_TLS}/consul-agent-ca-key.pem"
  chmod 0600 "${DIR_TLS}/consul-agent-ca-key.pem"
  ls ${DIR_TLS}/consul-agent-ca*.pem
}

tls_config_server() {
  server_index="${1}"
cat <<-EOF
[req]
req_extensions = v3_req
distinguished_name = dn
[dn]
CN = *.$DC.consul
[v3_req]
keyUsage = digitalSignature, keyEncipherment
basicConstraints=CA:FALSE
subjectAltName = @alt_names
[ alt_names ]
DNS.1 = $SUBDOMAIN-$server_index.$DOMAIN
DNS.2 = localhost
IP.1  = 127.0.0.1
EOF
}

gen_server_requests() {
  for i in $(seq 1 $SERVERS_COUNT); do
    WORK_DIR="${DIR_TLS}/server${i}"
    mkdir -p "${WORK_DIR}"
    openssl req -new -newkey rsa:2048 -verbose \
      -nodes -keyout "${WORK_DIR}/server${i}.${DC}.consul.key" \
      -out "${WORK_DIR}/server${i}.${DC}.consul.csr" \
      -subj "/CN=server.${DC}.consul"
  done
}

sign_server_requests() {
  for i in $(seq 1 $SERVERS_COUNT); do
    WORK_DIR="${DIR_TLS}/server${i}"
    tls_config_server "${i}" > "/tmp/server${i}.${DC}.consul.conf"
    openssl x509 -req -in "${WORK_DIR}/server${i}.${DC}.consul.csr" \
      -CA "${DIR_TLS}/consul-agent-ca.pem" \
      -CAkey "${DIR_TLS}/consul-agent-ca-key.pem" \
      -CAcreateserial \
      -days ${TTL} \
      -out "${WORK_DIR}/server${i}.${DC}.consul.crt" \
      -extfile /tmp/server${i}.${DC}.consul.conf \
      -extensions v3_req
  done
}

validate_server_signed() {
  for i in $(seq 1 $SERVERS_COUNT); do
    WORK_DIR="${DIR_TLS}/server${i}"
    openssl x509 -text -noout -in "${WORK_DIR}/server${i}.${DC}.consul.crt"
  done
}

gen_client_request() {
  WORK_DIR="${DIR_TLS}/client"
  mkdir -p "${WORK_DIR}"
  openssl req -new -newkey rsa:2048 \
    -nodes -keyout "${WORK_DIR}/client.${DC}.consul.key" \
    -out "${WORK_DIR}/client.${DC}.consul.csr" \
    -subj "/CN=client.${DC}.consul"
}

sign_client_request() {
  WORK_DIR="${DIR_TLS}/client"
  openssl x509 -req -in "${WORK_DIR}/client.${DC}.consul.csr" \
    -CA "${DIR_TLS}/consul-agent-ca.pem" \
    -CAkey "${DIR_TLS}/consul-agent-ca-key.pem" \
    -days ${TTL} \
    -out "${WORK_DIR}/client.${DC}.consul.crt"

}

validate_client_signed() {
  WORK_DIR="${DIR_TLS}/client"
  openssl x509 -text -noout -in "${WORK_DIR}/client.${DC}.consul.crt"
}

IS_CLIENT=false

gen_requests() {
  if [ "$IS_CLIENT" = true ]; then
    gen_client_request
  else
    gen_server_requests
  fi
  tree ${DIR_TLS}
}

sign_requests() {
  if [ "$IS_CLIENT" = true ]; then
    sign_client_request
  else
    sign_server_requests
  fi
  tree ${DIR_TLS}
}

validate_signed() {
  if [ "$IS_CLIENT" = true ]; then
    validate_client_signed
  else
    validate_server_signed 
  fi
}

while getopts ":hdg:crsvA" opt; do
  case $opt in
    d)
      set -x
      ;;
    g)
      last="${@: -1}"
      gen_ca "${OPTARG}" "${last}"
      ;;
    c)
      IS_CLIENT=true
      ;;
    r)
      gen_requests
		  ;;
    s)
      sign_requests
      ;;
    v)
      validate_signed | less
      ;;
    A)
      gen_requests && \
        sign_requests && \
        validate_signed | less
      ;;
    h)
      about
      ;;
    ?)
      echo "Invalid option: -$OPTARG" >&2
      about
      ;;
  esac
done
